# Copyright (c) 2018-2024, NVIDIA CORPORATION.
# Notes:
# - nccl package on rapidsai-nightly causes problems because rattler-build uses strict channel priority - rattler-build uses strict channel priority and it does not appear to be configurable, see https://github.com/prefix-dev/rattler-build/issues/343, so we need to make it work.
# - Various bits of string interpolation in the top variables don't seem to work yet. Still need to figure out how to achieve the same effect
# - Need to include git in the build env because the host git doesn't appear to be visible.
# - I'm not yet sure how you handle multiple outputs where one of them does all the building for reuse by other jobs downstream
# - Try using secrets instead of env

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split('.'))[:2] | join(".") }}
  cuda_version: ${{ (env.get('RAPIDS_CUDA_VERSION') | split('.'))[:2] | join(".") }}
  cuda_major: ${{ (env.get('RAPIDS_CUDA_VERSION') | split('.'))[0] }}
  date_string: ${{ env.get("RAPIDS_DATE_STRING") }}

recipe:
  version: ${{ version }}

source:
  path: ../../..

build:
  script:
    env:
      AWS_ACCESS_KEY_ID: ${{ env.get("AWS_ACCESS_KEY_ID") }}
      AWS_SECRET_ACCESS_KEY: ${{ env.get("AWS_SECRET_ACCESS_KEY") }}
      AWS_SESSION_TOKEN: ${{ env.get("AWS_SESSION_TOKEN") }}
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_KEY_PREFIX: ${{ "libcugraph-linux64" if linux64 else "libcugraph-aarch64" if aarch64 }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}

outputs:
  - package:
      name: libcugraph
    build:
      script: install_libcugraph.sh
      number: ${{ GIT_DESCRIBE_NUMBER }}
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ GIT_DESCRIBE_HASH }}_${{ GIT_DESCRIBE_NUMBER }}
    requirements:
      ignore_run_exports:
        from_package:
          - if: cuda_major == "11"
            then:
              - ${{ compiler('cuda11') }}
            else:
              - ${{ compiler('cuda') }}
              - cuda-cudart-dev
      build:
        - ${{ compiler('c') }}
        - if: cuda_major == "11"
          then:
            - ${{ compiler('cuda11') }} ${{ cuda_version }}
          else:
            - ${{ compiler('cuda') }}
        - cuda-version =${{ cuda_version }}
        - ${{ compiler('cxx') }}
        - cmake ${{ cmake_version }}
        - ninja
        - git
        - openmpi<5.0.3 # Required for building cpp-mgtests (multi-GPU tests)
        - ${{ stdlib("c") }}
      host:
        - if: cuda_major == "11"
          then:
            - cudatoolkit
            - cuda-nvtx =${{ cuda_version }}
            - cuda-profiler-api ${{ cuda11_cuda_profiler_api_host_version }}
            - libcublas ${{ cuda11_libcublas_host_version }}
            - libcublas-dev ${{ cuda11_libcublas_host_version }}
            - libcurand ${{ cuda11_libcurand_host_version }}
            - libcurand-dev ${{ cuda11_libcurand_host_version }}
            - libcusolver ${{ cuda11_libcusolver_host_version }}
            - libcusolver-dev ${{ cuda11_libcusolver_host_version }}
            - libcusparse ${{ cuda11_libcusparse_host_version }}
            - libcusparse-dev ${{ cuda11_libcusparse_host_version }}
          else:
            - cuda-nvtx-dev
            - cuda-profiler-api
            - cuda-cudart-dev
            - libcublas-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
        - cuda-version =${{ cuda_version }}
        - doxygen ${{ doxygen_version }}
        - libcudf =${{ minor_version }}
        - libcugraphops =${{ minor_version }}
        - libraft =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - conda-forge::nccl ${{ nccl_version }}
        - ucx-proc=*=gpu
        - rapids-build-backend>=0.3.1,<0.4.0.dev0
      run:
        - ${{ pin_compatible('cuda-version', upper_bound='x', lower_bound='x') }}
        - if: cuda_major == "11"
          then:
            - cuda-profiler-api ${{ cuda11_cuda_profiler_api_run_version }}
            - cudatoolkit
            - libcublas ${{ cuda11_libcublas_run_version }}
            - libcurand ${{ cuda11_libcurand_run_version }}
            - libcusolver ${{ cuda11_libcusolver_run_version }}
            - libcusparse ${{ cuda11_libcusparse_run_version }}
          else:
            - cuda-profiler-api
            - cuda-cudart
            - libcublas
            - libcurand
            - libcusolver
            - libcusparse
        - libcugraphops =${{ minor_version }}
        - libraft =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - conda-forge::nccl ${{ nccl_version }}
        - ucx-proc=*=gpu
    about:
      homepage: https://rapids.ai/
      repository: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph library
  - package:
      name: libcugraph_etl
    build:
      script: install_libcugraph_etl.sh
      number: ${{ GIT_DESCRIBE_NUMBER }}
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ GIT_DESCRIBE_HASH }}_${{ GIT_DESCRIBE_NUMBER }}
    requirements:
      ignore_run_exports:
        from_package:
          - if: cuda_major == "11"
            then:
              - ${{ compiler('cuda11') }}
            else:
              - ${{ compiler('cuda') }}
              - cuda-cudart-dev
      build:
        - ${{ compiler('c') }}
        - if: cuda_major == "11"
          then:
            - ${{ compiler('cuda11') }} ${{ cuda_version }}
          else:
            - ${{ compiler('cuda') }}
        - cuda-version =${{ cuda_version }}
        - ${{ compiler('cxx') }}
        - cmake ${{ cmake_version }}
        - ninja
        - openmpi<5.0.3 # Required for building cpp-mgtests (multi-GPU tests)
        - ${{ stdlib("c") }}
      host:
        - if: cuda_major == "11"
          then:
            - cudatoolkit
            - cuda-nvtx =${{ cuda_version }}
            - cuda-profiler-api ${{ cuda11_cuda_profiler_api_host_version }}
            - libcublas ${{ cuda11_libcublas_host_version }}
            - libcublas-dev ${{ cuda11_libcublas_host_version }}
            - libcurand ${{ cuda11_libcurand_host_version }}
            - libcurand-dev ${{ cuda11_libcurand_host_version }}
            - libcusolver ${{ cuda11_libcusolver_host_version }}
            - libcusolver-dev ${{ cuda11_libcusolver_host_version }}
            - libcusparse ${{ cuda11_libcusparse_host_version }}
            - libcusparse-dev ${{ cuda11_libcusparse_host_version }}
          else:
            - cuda-nvtx-dev
            - cuda-profiler-api
            - cuda-cudart-dev
            - libcublas-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
        - cuda-version =${{ cuda_version }}
        - doxygen ${{ doxygen_version }}
        - libcudf =${{ minor_version }}
        - libcugraphops =${{ minor_version }}
        - libraft =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - conda-forge::nccl ${{ nccl_version }}
        - ucx-proc=*=gpu
        - rapids-build-backend>=0.3.1,<0.4.0.dev0
      run:
        - ${{ pin_compatible('cuda-version', upper_bound='x', lower_bound='x') }}
        - ${{ pin_subpackage('libcugraph', exact=True) }}
        - if: cuda_major == "11"
          then:
            - cudatoolkit
          else:
            - cuda-cudart
        - libcudf =${{ minor_version }}
        - librmm =${{ minor_version }}
    about:
      homepage: https://rapids.ai/
      repository: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph_etl library
  - package:
      name: libcugraph-tests
    build:
      script: install_libcugraph_tests.sh
      number: ${{ GIT_DESCRIBE_NUMBER }}
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ GIT_DESCRIBE_HASH }}_${{ GIT_DESCRIBE_NUMBER }}
    requirements:
      ignore_run_exports:
        from_package:
          - if: cuda_major == "11"
            then:
              - ${{ compiler('cuda11') }}
            else:
              - ${{ compiler('cuda') }}
              - cuda-cudart-dev
      build:
        - ${{ compiler('c') }}
        - if: cuda_major == "11"
          then:
            - ${{ compiler('cuda11') }} ${{ cuda_version }}
          else:
            - ${{ compiler('cuda') }}
        - cuda-version =${{ cuda_version }}
        - ${{ compiler('cxx') }}
        - cmake ${{ cmake_version }}
        - ninja
        - openmpi<5.0.3 # Required for building cpp-mgtests (multi-GPU tests)
        - ${{ stdlib("c") }}
      host:
        - if: cuda_major == "11"
          then:
            - cudatoolkit
            - cuda-nvtx =${{ cuda_version }}
            - cuda-profiler-api ${{ cuda11_cuda_profiler_api_host_version }}
            - libcublas ${{ cuda11_libcublas_host_version }}
            - libcublas-dev ${{ cuda11_libcublas_host_version }}
            - libcurand ${{ cuda11_libcurand_host_version }}
            - libcurand-dev ${{ cuda11_libcurand_host_version }}
            - libcusolver ${{ cuda11_libcusolver_host_version }}
            - libcusolver-dev ${{ cuda11_libcusolver_host_version }}
            - libcusparse ${{ cuda11_libcusparse_host_version }}
            - libcusparse-dev ${{ cuda11_libcusparse_host_version }}
          else:
            - cuda-nvtx-dev
            - cuda-profiler-api
            - cuda-cudart-dev
            - libcublas-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
        - cuda-version =${{ cuda_version }}
        - doxygen ${{ doxygen_version }}
        - libcudf =${{ minor_version }}
        - libcugraphops =${{ minor_version }}
        - libraft =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - conda-forge::nccl ${{ nccl_version }}
        - ucx-proc=*=gpu
        - rapids-build-backend>=0.3.1,<0.4.0.dev0
      run:
        - ${{ pin_compatible('cuda-version', upper_bound='x', lower_bound='x') }}
        - ${{ pin_subpackage('libcugraph_etl', exact=True) }}
        - ${{ pin_subpackage('libcugraph', exact=True) }}
        - if: cuda_major == "11"
          then:
            - cudatoolkit
          else:
            - cuda-cudart
    about:
      homepage: https://rapids.ai/
      repository: https://github.com/rapidsai/cugraph
      license: Apache-2.0
      license_file: ../../../LICENSE
      summary: libcugraph test & benchmark executables
